# Generated by Django 3.2.3 on 2021-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=150)),
                ('Marca', models.CharField(max_length=100)),
                ('Ano', models.IntegerField()),
                ('Preço', models.IntegerField()),
            ],
        ),
    ]
